"""Track A anchor rows

Revision ID: 393b0d9c9ffd
Revises: 8e08d095c59e  # track_a_asset_naming
Create Date: 2026-04-25

Inserts the manual anchor at 2026-04-25 into both:
  - portfolio_snapshots (archive series)
  - portfolio_performance_snapshots (performance series, base 100.0)

Values sourced from the user's Toss app (verified read-only audit, see
docs/superpowers/specs/2026-04-25-portfolio-anchor-design.md §6.3).

Idempotent via INSERT WHERE NOT EXISTS + UPDATE for archive row.
"""
from datetime import date, datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393b0d9c9ffd'
down_revision: Union[str, Sequence[str], None] = '8e08d095c59e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ANCHOR_DATE = date(2026, 4, 25)


def upgrade() -> None:
    # Archive anchor row — total wealth + invested + cash decomposition
    op.execute(
        sa.text("""
            INSERT INTO portfolio_snapshots (date, total_value, invested_capital, cash_balance)
            SELECT :anchor_date, 21353133.0, 21253002.0, 100131.0
            WHERE NOT EXISTS (
                SELECT 1 FROM portfolio_snapshots WHERE date = :anchor_date
            )
        """).bindparams(anchor_date=ANCHOR_DATE)
    )

    # If a row already exists at this date (e.g., from prior cron run with
    # placeholder values), update it to the verified anchor values. We keep
    # this UPDATE separate so a fresh INSERT and an existing-row UPDATE are
    # both handled.
    op.execute(
        sa.text("""
            UPDATE portfolio_snapshots
            SET total_value = 21353133.0,
                invested_capital = 21253002.0,
                cash_balance = 100131.0
            WHERE date = :anchor_date
        """).bindparams(anchor_date=ANCHOR_DATE)
    )

    # Performance anchor row — base 100.0, source_version flags it for cron protection
    op.execute(
        sa.text("""
            INSERT INTO portfolio_performance_snapshots
                (date, performance_value, benchmark_value, daily_return, alpha,
                 coverage_start_date, coverage_status, source_version, updated_at)
            SELECT :anchor_date, 100.0, 100.0, 0.0, 0.0,
                   :anchor_date, 'ready', 'manual-anchor-v1', :now
            WHERE NOT EXISTS (
                SELECT 1 FROM portfolio_performance_snapshots WHERE date = :anchor_date
            )
        """).bindparams(anchor_date=ANCHOR_DATE, now=datetime.now(timezone.utc))
    )


def downgrade() -> None:
    op.execute(
        sa.text("""
            DELETE FROM portfolio_performance_snapshots
            WHERE date = :anchor_date AND source_version = 'manual-anchor-v1'
        """).bindparams(anchor_date=ANCHOR_DATE)
    )
    # Note: archive row is not removed on downgrade because it may have been
    # generated by the daily cron prior to this migration. The downgrade
    # leaves archive series intact.
