"""Add system_cache table

Revision ID: 8d1789f7c374
Revises: f1a9c3d8e210
Create Date: 2026-04-06 21:01:59.170457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1789f7c374'
down_revision: Union[str, Sequence[str], None] = 'f1a9c3d8e210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_cache',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_cache_key'), 'system_cache', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_cache_key'), table_name='system_cache')
    op.drop_table('system_cache')
    # ### end Alembic commands ###
