"""ELT Pipeline Schema

Revision ID: a874b8e65364
Revises: ebdee97d2ac2
Create Date: 2026-03-22 01:48:33.235431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a874b8e65364'
down_revision: Union[str, Sequence[str], None] = 'ebdee97d2ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_daily_prices',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'ticker')
    )
    op.add_column('portfolio_snapshots', sa.Column('invested_capital', sa.Float(), nullable=True))
    op.alter_column('portfolio_snapshots', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index(op.f('ix_portfolio_snapshots_date'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_id'), table_name='portfolio_snapshots')
    op.drop_column('portfolio_snapshots', 'invested_amount')
    op.drop_column('portfolio_snapshots', 'id')
    op.drop_column('portfolio_snapshots', 'daily_return')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_snapshots', sa.Column('daily_return', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('portfolio_snapshots', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('portfolio_snapshots', sa.Column('invested_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_portfolio_snapshots_id'), 'portfolio_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_date'), 'portfolio_snapshots', ['date'], unique=True)
    op.alter_column('portfolio_snapshots', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('portfolio_snapshots', 'invested_capital')
    op.drop_table('raw_daily_prices')
    # ### end Alembic commands ###
